backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images" 
#media_folder: "static/images/uploads"
public_folder: "assets/images"
collections:
  #Blog posts:
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Blog" # Used in the UI
  #   folder: "_posts/blog" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "Body", name: "body", widget: "markdown"}

  #Pages:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Contact Page"
        name: "contact"
        file: "contact.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Information for Tutors"
        name: "fortutors"
        file: "fortutors.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Resources"
        name: "resources"
        file: "resources.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - label: "Staff"
        name: "staff"
        file: "staff.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "info"
            widget: "markdown"
    
      
  # - name: "page"
  #   label: "Page"
  #   folder: "pages"
  #   sort: "title:asc"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - {label: "Permalink", name: "permalink", widget: "hidden"}
  #     - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}

    #Posts:
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

    #Tiles
  - label: "Tile Settings - Home Page"
    name: "tile"
    files:
      - label: "Tile Settings"
        name: "tile"
        file: "_data/tile.yml"
        fields:
          - label: "Tile Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: display_name, widget: string}
              - {label: Link, name: url, widget: string}
              - {label: Image, name: img, widget: image}
              - {label: Description, name: abst, widget: string}
              
  - label: "Staff" # Used in routes, ie.: /admin/collections/:slug/edit
    name: "staff" # Used in the UI, ie.: "New Post"
    folder: "_staff" # The path to the folder where the documents are stored
    sort: "lastName:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Last Name", name: "lastName", widget: "string"}
      - {label: "Category",name: "category",widget: "string"} #TODO: Figure out how to make a 2 option list
      - {label: "Major", name: "major", widget: "string", required: false}
      - {label: "Bio", name: "body", widget: "markdown", required: false}

